system:
  ip: ""
  port: 8080
  env: "dev"
mysql:
  host: 127.0.0.1 # （必须）连接数据库的地址
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: grs_db  # 数据库名
  username: root
  password: 12345678
  logLevel: info
